version: "3.10-slim"

services:
  web:
    build: .
    command: gunicorn drf_auth_project.wsgi:application --bind 0.0.0.0:8000 --workers 4

    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=postgres

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data